name: bada
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  sqflite: ^2.3.2
  # geolocation: ^1.1.2
  flutter_dotenv: ^5.1.0
  dio: ^5.4.1
  json_serializable: ^6.7.1
  platform: ^3.1.4
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  encrypt: ^5.0.3
  lottie: ^3.1.0
  go_router: ^13.2.0
  cupertino_icons: ^1.0.6
  kakao_flutter_sdk: ^1.9.0 # 전체 추가
  kakao_flutter_sdk_common: ^1.9.0 # 공통 API 패키지
  kakao_flutter_sdk_user: ^1.9.0 # 카카오 로그인 API 패키지
  provider: ^6.1.2
  flutter_naver_login: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/
    - assets/gif/
    - assets/lottie/
    - assets/dummydata/


  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 900
    - family: Spoqa
      fonts:
        - asset: assets/fonts/Spoqa/SpoqaHanSansNeo-Regular.ttf
        - asset: assets/fonts/Spoqa/SpoqaHanSansNeo-Bold.ttf
          weight: 900